version: '3'
services:
  app:
    container_name: red_coins
    build: .
    ports: 
      - 3333:3333 
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - tempate-echo-gorm-postgres          
    networks:
      - tempate-echo-gorm

  tempate-echo-gorm-postgres:
    image: postgres:latest
    container_name: full_db_postgres
    environment:
      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST} 
    ports:
      - '5433:5433'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - tempate-echo-gorm
    
volumes:
  api:
  database_postgres:

# Networks to be created to facilitate communication between containers
networks:
  tempate-echo-gorm:
    driver: bridge
